# Paths
docs_dir: docs
site_dir: site

# Project information
site_name: Symlex
site_description: A lean framework stack for agile Web development based on Symfony and Vuetify
site_author: Symlex.org
site_url: https://docs.symlex.org/zh/latest

# Repository
repo_name: symlex/symlex
repo_url: https://github.com/symlex/symlex
edit_uri: ""

# Copyright
copyright: 'Made with ❤ in Berlin 中文翻译由 Tuzi Moe 提供'

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  feature:
    tabs: true
  palette:
    primary: blue grey
    accent: cyan
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/favicon.ico
  logo: img/favicon.ico

# Customization
extra:
  social:
    - type: commenting
      link: https://gitter.im/symlex/community
    - type: twitter
      link: https://twitter.com/lastzero
    - type: linkedin
      link: https://www.linkedin.com/in/lastzero/
    - type: globe
      link: https://symlex.org/
    - type: github-alt
      link: https://github.com/symlex

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: pymdownx.emoji.emojione
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 欢迎: index.md
  - 性能: performance.md
  - 历史: history.md
  - 妥协与否: tradeoffs.md
  - 团队: team.md
  - 联系我们: contact.md
  - 贡献: contribute.md
  - 致谢: credits.md
  - License: license.md
  - Mac OS X: osx.md
  - 框架:
    - 简易入门: framework.md
    - 配置框架: framework/config.md
    - 启动框架: framework/kernel.md
    - 路由 & Twig: framework/routing.md
    - 指令: framework/cli.md
    - 网页前端: framework/frontend.md
    - 网页控制器: framework/web.md
    - REST 控制器: framework/rest.md
    - 输入变量: framework/forms.md
    - 持久层: framework/models.md
    - 错误: framework/errors.md
    - Symfony 捆绑包: framework/bundles.md
    - 单元测试: framework/unit-tests.md
    - 验收测试: framework/acceptance-tests.md
  - 核心部分:
    - 介绍: core.md
    - 内核: core/kernel.md
    - 路由: core/routers.md
  - DI 微内核:
    - 介绍: di-microkernel.md
    - 配置: di-microkernel/config.md
    - 贡献: di-microkernel/contribute.md
  - 输入变量:
    - 介绍: input-validation.md
    - 创建表单: input-validation/definition.md
    - Field Properties: input-validation/properties.md
    - REST 示例: input-validation/example.md
    - API: input-validation/api.md
    - 妥协与否: input-validation/tradeoffs.md
    - 贡献: input-validation/contribute.md
  - Doctrine ActiveRecord:
    - 介绍: doctrine-active-record.md
    - 示例: doctrine-active-record/examples.md
    - 生产模式: doctrine-active-record/models.md
    - Data Access Objects: doctrine-active-record/daos.md
    - Search 请求: doctrine-active-record/search.md
    - 单元测试: doctrine-active-record/tests.md
    - 妥协与否: doctrine-active-record/tradeoffs.md
    - 贡献: doctrine-active-record/contribute.md
